version: "3"
services:
  db:
    image: mysql:latest
    restart: "always"
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "flask-crud"
      MYSQL_ROOT_PASSWORD: "admin123"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - /home/caefleury/Documents/Projects/mysql:/var/lib/mysql
